name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: nothub
authors: [ AlexProgrammerDE, MaybeEther, SooStrator ]
main: not.hub.safetpa.Plugin
api-version: 1.20

commands:
  tpa:
    description: Send TP Request
    usage: /tpa <name> .. or .. /tpask <name>
    aliases: [ tpask ]
    permission: tpa.tpa
    permission-message: Insufficient permissions, you should harass your admin because of this!
  tpy:
    description: Accept TP Request
    usage: /tpy <name> .. or .. /tpaccept <name>
    aliases: [ tpaccept ]
    permission: tpa.tpy
    permission-message: Insufficient permissions, you should harass your admin because of this!
  tpn:
    description: Deny TP Request
    usage: /tpn <name> .. or .. /tpdeny <name>
    aliases: [ tpdeny ]
    permission: tpa.tpn
    permission-message: Insufficient permissions, you should harass your admin because of this!
  tpt:
    description: Toggle TP Requests
    usage: /tpt .. or .. /tptoggle
    aliases: [ tptoggle ]
    permission: tpa.tpt
    permission-message: Insufficient permissions, you should harass your admin because of this!
  tpi:
    description: Ignore TP requests
    usage: /tpi <name> .. or .. /tpignore <name>
    aliases: [ tpignore ]
    permission: tpa.tpi
    permission-message: Insufficient permissions, you should harass your admin because of this!

permissions:
  tpa.tpa:
    description: Send TP Request
    default: true
  tpa.tpy:
    description: Accept TP Request
    default: true
  tpa.tpn:
    description: Deny TP Request
    default: true
  tpa.tpt:
    description: Toggle TP Requests
    default: true
  tpa.tpi:
    description: Ignore TP Requests
    default: true
